[package]
name = "rix-lang"
version = "0.1.0"
edition = "2024"

[dependencies]
lalrpop-util = { version = "0.22.2", features = ["lexer"] }
inkwell = { version = "0.6.0", features = ["llvm18-1"] }

[build-dependencies]
lalrpop = "0.22.2"
